### ISSUE TITLE
Conflictos de merge

### ISSUE THREAD

**Issue by DanielSolis00209020** [UCASV/proyecto-final-grupo-1#3]
Me aparecieron conflictos en el merge, y creo que ya los solucione pero hay uno que me falta o no se donde esta.

**Comment by Acostam331** [comment]
Esta en el diseñador del formulario de crear cita.

**Comment by DanielSolis00209020** [comment]
Ah es cierto no revise los designer, gracias ahorita lo corrijo y hago push.

**Comment by Acostam331** [comment]
ok.
