### ISSUE TITLE
Error instalador

### ISSUE THREAD

**Issue by DanielSolis00209020** [UCASV/proyecto-final-grupo-1#5]
@Aguirre221 El instalador no me sirve, presenta fallos y creo que es por la versión de software seleccionado

**Comment by DanielSolis00209020** [comment]
@Acostam331 a vos te funciona el instalador?

**Comment by Acostam331** [comment]
@DanielSolis00209020 No me funciona, reverti el commit del instalador.

**Comment by DanielSolis00209020** [comment]
@Acostam331 a volver a hacerlo pues?, quien lo hace?

**Comment by Acostam331** [comment]
@Aguirre221

**Comment by carlosxmerca** [comment]
Parece que el error es por compatibilidad, no esta reconociendo el paquete de sql...
